# a=int(input("enter the no."))
# print("hexadecimal of",str(hex(a)))
# print("octadecimal of", str(oct(a)))
# print("square root", a**0.5)
# print("\a")
# print("hello world\n" *5)
# print(10* "hello motto\n")
# print("addi" +"5")
# a="I am the kin of the universe"
# print(a)
# print(a[1])
# print(a[4:20])
# print(a[0:40])
# print(len(a))
Tup=('a', 'b','c', 2.5 ,679)
Tuo2=(2,67,'sd','rd')
print(Tup)
print(Tup[3:4])
print(Tup[0:1])
print(Tup+Tuo2)